seasarorg/mayaa

- src-api/org/seasar/mayaa/cycle/CycleWriter.java
- src-api/org/seasar/mayaa/cycle/ServiceCycle.java
- src-api/org/seasar/mayaa/engine/specification/NodeTreeWalker.java
- src-api/org/seasar/mayaa/engine/specification/ParentSpecificationResolver.java
- src-api/org/seasar/mayaa/source/SourceDescriptor.java
- src-impl/org/seasar/mayaa/impl/MayaaApplicationFilter.java
- src-impl/org/seasar/mayaa/impl/builder/PathRelativeAdjusterImpl.java
- src-impl/org/seasar/mayaa/impl/builder/TemplateBuilderImpl.java
- src-impl/org/seasar/mayaa/impl/builder/TemplateNodeHandler.java
- src-impl/org/seasar/mayaa/impl/builder/parser/TemplateParser.java
- src-impl/org/seasar/mayaa/impl/cycle/CycleWriterImpl.java
- src-impl/org/seasar/mayaa/impl/cycle/StandardScope.java
- src-impl/org/seasar/mayaa/impl/cycle/script/ScriptBlockIterator.java
- src-impl/org/seasar/mayaa/impl/cycle/script/rhino/direct/AbstractGetterScript.java
- src-impl/org/seasar/mayaa/impl/cycle/script/rhino/direct/GetterScriptFactory.java
- src-impl/org/seasar/mayaa/impl/cycle/web/MockServletContext.java
- src-impl/org/seasar/mayaa/impl/engine/EngineUtil.java
- src-impl/org/seasar/mayaa/impl/engine/RenderUtil.java
- src-impl/org/seasar/mayaa/impl/engine/TemplateImpl.java
- src-impl/org/seasar/mayaa/impl/engine/processor/ElementProcessor.java
- src-impl/org/seasar/mayaa/impl/engine/processor/InsertProcessor.java
- src-impl/org/seasar/mayaa/impl/engine/processor/WriteProcessor.java
- src-impl/org/seasar/mayaa/impl/engine/specification/SpecificationUtil.java
- src-impl/org/seasar/mayaa/impl/standalone/FileGenerator.java
- src-impl/org/seasar/mayaa/impl/standalone/FileSearchRenderer.java
- src-impl/org/seasar/mayaa/impl/util/IOUtil.java
- src-impl/org/seasar/mayaa/impl/util/ObjectUtil.java
- src-impl/org/seasar/mayaa/impl/util/StringUtil.java
- src-impl/org/seasar/mayaa/impl/util/WeakValueHashMap.java
mvn package でビルドする際にJavadocエラーや警告が発生してパッケージが生成できないためJavadocコメントを修正。
> Mavenビルド時に発生するJavadocエラーの修正

- pom.xml
- src/test/java/org/seasar/mayaa/functional/EngineTestBase.java
- src/test/java/org/seasar/mayaa/impl/cycle/scope/StubApplicationScopeSupport.java
- src/test/java/test/PerformanceTest.java
- src/test/java/test/SlowTest.java
遅いテストを含めるとき `mvn test -PwithSlowTest`
パフォーマンステストの場合 `mvn test -PwithPerformanceTest`
パフォーマンステストはJFR有効としているためJDKは AdoptOpenJDK11 以降のみ。
> 遅いテストとパフォーマンステストにカテゴリ付与

- CHANGELOG.md
- src-impl/org/seasar/mayaa/impl/cycle/script/rhino/ScriptEnvironmentImpl.java
- src-impl/org/seasar/mayaa/impl/util/WeakValueHashMap.java
- src/test/java/org/seasar/mayaa/impl/cycle/script/rhino/ScriptEnvironmentTest.java
- src/test/java/org/seasar/mayaa/impl/util/WeakValueHashMapTest.java
- src/test/java/org/seasar/mayaa/regressions/issue14/Issue14ReproductionTest.groovy
- src/test/java/org/seasar/mayaa/regressions/issue14/Issue14ReproductionTest.java
WeakValueHashMapは値を弱参照として保持することでScriptEnvironmentImpl内でキャッシュとして利用されているが、いくつかの課題がある。
1. #14 で指摘されているように同期化が完全には実施できていない
2. 直近で参照された値を固定枠で（デフォルトは128個）を強参照として保持させるようにしているが、同じ値を何度も参照した場合でもこの枠を消費してしまうため、複数のスクリプトが高頻度で参照されている場合のキャッシュヒット率が高くならない。枠の意味があまりないように見受けられる。
したがって、LRUで固定個数を保持しながら、LRUで吐き出されたものを弱参照で保持するように再実装した。
新実装ではWeakValueHashMap単体で同期化処理を行うようにしている。
また、強参照で保持させる個数は実行中に変更できるようにしている。
（運用中にメモリ問題が発生した場合に外部から縮小させるようにしておく）
> WeakValueHashMapの再実装

- .classpath
- .project
- src/test/java/org/seasar/mayaa/functional/EngineTest.java
- src/test/java/org/seasar/mayaa/impl/cycle/script/rhino/ScriptEnvironmentTest.java
- src/test/java/org/seasar/mayaa/impl/cycle/script/rhino/WEB-INF/org.seasar.mayaa.provider.ServiceProvider
- src/test/resources/it-case/script/java-bridge/expected.html
- src/test/resources/it-case/script/java-bridge/target.html
- src/test/resources/it-case/script/java-bridge/target.mayaa
スクリプト実行を行う`Engine`のテストおよび `ScriptEnvironmentImpl` のテストを追加
IDE上でcontext/WEB-INF 配下の jar が pom.xml 定義のjarが競合するため .classpath からは除外した。
(WAR配布を今後も行わないなら context ディレクトリは以下は不要と思います)
> スクリプト実行のテストを追加

- CHANGELOG.md
- pom.xml
- src/main/java-templates/org/seasar/mayaa/impl/Version.java
org.seasar.mayaa.impl.Version.MAYAA_VERSION で参照可能
> Mayaaのバージョンをmvnビルド時にソースに埋め込む

- doc/TESTING.md
- src/test/java/org/seasar/mayaa/test/integration/CustomTagITCase.java
#44 でケースが通らず期待値を修正していたが、別の修正中コードが影響していたことが判明したため、元に戻した。
> インテグレーションテスト期待値を修正

- pom.xml
- src-impl/org/seasar/mayaa/impl/source/SystemIDFileSearchIterator.java
pom.xml で java7 ターゲットにしているものの、手元では java8 コンパイラを使用していたことに起因して
Java8ではデフォルトメソッドとなっていたIterator.remove の未実装箇所の検知が漏れた。
Github Action で使用するJDKのバージョンを 7 に変更したことにより発覚した。
> Java7互換性の修正漏れ

- src-impl/org/seasar/mayaa/impl/builder/library/entity/javaee_7.xsd
- src-impl/org/seasar/mayaa/impl/builder/library/entity/javaee_web_services_client_1_4.xsd
- src-impl/org/seasar/mayaa/impl/builder/library/entity/jsp_2_3.xsd
- src-impl/org/seasar/mayaa/impl/builder/library/entity/web-app_4_0.xsd
- src-impl/org/seasar/mayaa/impl/builder/library/entity/web-common_4_0.xsd
- src/test/java/org/seasar/mayaa/impl/builder/library/scanner/WEB-INF25/web.xml
- src/test/java/org/seasar/mayaa/impl/builder/library/scanner/WEB-INF30/web.xml
- src/test/java/org/seasar/mayaa/impl/builder/library/scanner/WEB-INF31/web.xml
- src/test/java/org/seasar/mayaa/impl/builder/library/scanner/WEB-INF40/web.xml
- src/test/java/org/seasar/mayaa/impl/builder/library/scanner/WebXmlAliasSourceScannerTest.java
#50 への対応。
Servlet 4.0 へも合わせて対応する。
なお、web.xml からタグライブラリの定義を読み取らなくていい場合でも必要となってしまうため、
将来的に設定で読み取り実施するかの切り替えをできるようにしておくと、web.xmlをパースするための
サーブレットバージョンへの追従が不要になるかもしれない。
> Servlet 3.1 と 4.0 の web.xml がパースできるようにする

- src-impl/org/seasar/mayaa/impl/util/IOUtil.java
- src/test/java/org/seasar/mayaa/impl/util/IOUtilTest.java
URLエンコードされる文字を含むsystemIDのファイル実体が参照できない。
仕様として systemID にURLエンコードされる文字を含むことがあり得るのかどうか。
影響範囲はClassLoader.getResource(String)で取得されたURLオブジェクトを受け取っている箇所であり、
現状ではClassLoaderSourceDescriptorから参照されるもののみ。
テストケースの見直しにより検出したもの。
> URLエンコードされる文字を含むsystemIDのファイル実体が参照できない

- src-api/org/seasar/mayaa/ParameterAware.java
- src-impl/org/seasar/mayaa/impl/AutoPageBuilder.java
- src-impl/org/seasar/mayaa/impl/CONST_IMPL.java
- src-impl/org/seasar/mayaa/impl/engine/EngineUtil.java
- src-impl/org/seasar/mayaa/impl/engine/SpecificationCache.java
- src-impl/org/seasar/mayaa/impl/engine/specification/SpecificationImpl.java
- src-impl/org/seasar/mayaa/impl/source/FileSourceDescriptor.java
- src-impl/org/seasar/mayaa/impl/source/PageSourceFactoryImpl.java
ParameterAwareImplに対するSerializableが強すぎて、ほぼ全てのクラスがserialVersionUIDを要求されている状態であるため、
Serializableをつけるインタフェースを再調整する。
本件はそのための準備として ParameterAware インタフェースから IS_SECURE_WEB の判定参照をEngineUtilに移動する。
> IS_SECURE_WEB 設定をParameterAwareからEngineUtilに移動

- .classpath
- .project
- src-impl/org/seasar/mayaa/impl/provider/factory/ParameterTagHandler.java
- src-impl/org/seasar/mayaa/impl/source/DynamicRegisteredSourceHolder.java
- src-impl/org/seasar/mayaa/impl/source/InMemorySourceDescriptor.java
- src-impl/org/seasar/mayaa/impl/source/PageSourceFactoryImpl.java
- src/integration-test/resources/META-INF/org.seasar.mayaa.source.PageSourceFactory
- test-war/pom.xml
主な用途はテスト用でテストケース内で下記のような利用方法を想定。
```java
final String DIR = "/it-case/parser/dynamic/";
DynamicRegisteredSourceHolder.registerContents(DIR + "target.html", 
"<!doctype html>\n" +
"<html>" +
"<DIV>${var a='no body';}${a.toUpperCase()}</DIV>" +
"</html>"
);
DynamicRegisteredSourceHolder.registerContents(DIR + "expected.html", 
"<!DOCTYPE html>\n" +
"<html>" +
"<div>NO BODY</div>" +
"</html>"
);
execAndVerify(DIR + "target.html", DIR + "expected.html", null);
DynamicRegisteredSourceHolder.unregisterAll();
```
org.seasar.mayaa.source.PageSourceFactory に `dynamic` というパラメータを追加することで追加される。
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factory PUBLIC "-//The Seasar Foundation//DTD Mayaa Factory 1.0//EN" "http://mayaa.seasar.org/dtd/mayaa-factory_1_0.dtd">
<factory>
<parameter …
```
> 動的に登録されたインメモリコンテンツを返却するSourceHolderを追加

- pom.xml
Java8 でないコンパイラでビルドした時に標準JavaクラスAPIが使われていたのを修正
> Java8 向けのAPI利用に制限する。

- src-impl/org/seasar/mayaa/impl/builder/library/LibraryManagerImpl.java
- src-impl/org/seasar/mayaa/impl/builder/library/message.properties
- src-impl/org/seasar/mayaa/impl/builder/library/scanner/FolderSourceScanner.java
- src-impl/org/seasar/mayaa/impl/builder/library/scanner/ResourceScanner.java
- src/test/java/org/seasar/mayaa/functional/engine/WEB-INF/org.seasar.mayaa.provider.ServiceProvider
- src/test/java/org/seasar/mayaa/impl/builder/library/scanner/ResourceScannerTest.java
`ResourceScanner`はクラスパス内の指定パターンのファイルを列挙する。
列挙はJARファイル内のファイルも対象であるが、クラスパスとして多くのJARが指定されていると必要以上に時間がかかるため
含めるJARファイル名、除外するファイル名を明示的に指定できるようにする。
`ResourceScanner`が使用されているのは org.seasar.mayaa.provider.ServiceProvider 内の `libraryManager`エレメント内のみ。
`includeJar`および`excludeJar`パラメータ仕様を追加した。
*などのGLOBパターンが利用可能。
記述順に上からJARファイル名を評価し、最初に合致したパラメータ指定もって含めるか、含めないかを判断する。
いずれにも合致しない場合は含める。（既存の挙動と互換性がある）
```xml
<scanner class="org.seasar.mayaa.impl.builder.library.scanner.ResourceScanner">
<parameter name="root" value="META-INF/"/>
<parameter name="ignore" value="META-INF/MANIFEST.MF"/>
<parameter name="extension" value=".mld"/>
<parameter name="extension" value=".tld"/>
<parameter name="includeJar" value="taglibs-standard-*.jar"/>
<parameter name="excludeJar" value="*"/>
</scanner>
``` …
> ResourceScannerで全てのJarをスキャンしないように除外指定できる

- src-api/org/seasar/mayaa/engine/Page.java
- src-api/org/seasar/mayaa/engine/processor/TemplateProcessor.java
- src-impl/org/seasar/mayaa/impl/engine/PageImpl.java
- src-impl/org/seasar/mayaa/impl/engine/processor/ElementProcessor.java
- src-impl/org/seasar/mayaa/impl/engine/processor/JspProcessor.java
- src-impl/org/seasar/mayaa/impl/engine/processor/TemplateProcessorSupport.java
Fixes #95 の方針とし、 interface定義自体は @deprecated として残しつつ、実装は空にする。
> TemplateProcessor.notifyBeginRenderが実質的に呼ばれていない

- src-impl/org/seasar/mayaa/impl/engine/processor/ElementProcessor.java
- src/test/resources/it-case/engine/script/expected.html
- src/test/resources/it-case/engine/script/target.html
Fixes #13
下記のようにInformalPropertyの属性値として埋め込まれている場合に変数の文字列化に影響があった。
`ElementProcessor.getInformalExpectedClass()` を明示的に実装し、文字列を指定することで解決。
HTMLソース
```html
<span class="script${nine}" data-value="${ nine }">${ nine }</span>
<span class="script${ten}" data-value="${ ten }">${ ten }</span>
```
Mayaa生成後（問題解消前）
```html
<span class="script9" data-value="9">9</span>
<span class="script10.0" data-value="10.0">10</span>
```
Mayaa生成後（問題解消後）
```html
<span class="script9" data-value="9">9</span>
<span class="script10" data-value="10">10</span>
```
> [mayaa-user:1087] 独自プロセッサーを使うとエラーが発生する場合がある

- pom.xml
Accept-Languageが送られないことでfmt:formatNumberがpatternを処理せず integration-testしてしまうため。
> Selenideをアップデート

- pom.xml
- src-impl/org/seasar/mayaa/impl/builder/parser/HtmlStandardScanner.java
- src/test/java/org/seasar/mayaa/functional/engine/ParserTest.java
WHATWGで定義されているパーサのルールによると HTMLファイルのパースにおいて属性名は `/`, `>`, `=` 以外の文字が利用できるようになっている。NekoHTML で許容されていなかった `@` などの文字も使用できるようになっているが、Mayaaにおいて特別な意味を持つ `${式}` だけは除外するようにする。
https://html.spec.whatwg.org/multipage/parsing.html#attribute-name-state
> 新パーサで使用できる属性名パターンのバリデーションを追加

- src-impl/org/seasar/mayaa/impl/builder/library/scanner/DefaultSourceScanner.java
- src-impl/org/seasar/mayaa/impl/builder/library/scanner/FolderSourceScanner.java
- src-impl/org/seasar/mayaa/impl/builder/library/scanner/JarSourceScanner.java
- src-impl/org/seasar/mayaa/impl/builder/library/scanner/MetaInfSourceScanner.java
- src-impl/org/seasar/mayaa/impl/builder/library/scanner/ResourceScanner.java
- src-impl/org/seasar/mayaa/impl/builder/library/scanner/WebXMLTaglibSourceScanner.java
- src-impl/org/seasar/mayaa/impl/provider/ProviderFactoryImpl.java
- src/test/resources/jul.properties
- test-war/src/main/resources/jboss-logging.properties
- test-war/src/main/resources/logging.properties
- test-war/src/main/webapp/WEB-INF/org.seasar.mayaa.provider.ServiceProvider
ライブラリファイルのスキャンおよびServiceProviderファイル読み込みのログを出力しました。
必要以上に読み込み量が多くなっていないかを確認できるようにするためです。
ログレベルは DEBUG にしています。
ロガー名は org.seasar.mayaa.impl.builder.library から始まりますので
JULの場合で個別に出力するとき下記のようにしてみてください
logging.properties
```
org.seasar.mayaa.level=INFO
org.seasar.mayaa.impl.builder.library.level=FINE
```
> ライブラリファイルのスキャンおよびServiceProviderファイル読み込みのログを出力

- src-impl/org/seasar/mayaa/impl/builder/library/scanner/WebInfSourceScanner.java
- src-impl/org/seasar/mayaa/impl/provider/factory/org.seasar.mayaa.provider.ServiceProvider
- src/integration-test/webapp/WEB-INF/org.seasar.mayaa.provider.ServiceProvider
- src/test/java/org/seasar/mayaa/impl/builder/library/scanner/WebInfSourceScannerTest.java
- test-war/src/main/resources/jboss-logging.properties
- test-war/src/main/webapp/WEB-INF/org.seasar.mayaa.provider.ServiceProvider
Webアプリケーションのコンテキスト内のリソースを走査してライブラリファイルを検出するための`SourceScanner`実装。
走査対象は WEB-INF配下のリソースで、lib内のJARファイルも走査対象となる。
ServiceProviderの設定ファイルで以下のように設定することで、走査対象のライブラリファイルを指定することができる。
設定は記述順で評価され、最初に合致したものが採用される。
`include`と`exclude`は `/WEB-INF/`を基準としてライブラリファイル(tld,mld)を検出対象(include)または除外対象(exclude)するためのGlobパターンを指定する。記述順に評価され最初に合致したもので判定される。
どちらのパターンも指定されない場合は`include="**/*.{tld,mld}"`のみが指定されたものとみなす。
`includeJar`と`excludeJar`で走査対象JARファイルのWEB-INF/libを基準としたファイル名部分のGlobパターンを指定する。
どちらのパターンも指定されない場合は `includeJar="*.jar"` のみが指定されたものとみなす。
`includeInJarMetaInf`と`excludeInJarMetaInf`で読み込み対象とするライブラリファイルパスのJARファイル内のMETA-INFを基準としたGlobパターンを指定する。
どちらのパターンも指定されない場合は `includeInJarMetaInf="*.{tld,mld}"` のみが指定されたものとみなす。
記述例
```xml
<scanner class="org.seasar.mayaa.impl.builder.library.scanner.WebInfSourceScanner"> …
```
> WEB-INF配下を明示指定でスキャンできるWebInfSourceScannerを新設

- src-impl/org/seasar/mayaa/impl/builder/BuilderUtil.java
- src-impl/org/seasar/mayaa/impl/builder/SpecificationNodeHandler.java
- src-impl/org/seasar/mayaa/impl/builder/parser/HtmlStandardScanner.java
- src/test/java/org/seasar/mayaa/functional/engine/ParserTest.java
エレメント名の先頭文字として許されない文字がある場合は次の開始タグまではテキストノードとして扱われますが、閉じタグの先頭文字として許されない文字の場合はHTMLコメントとして出力されます。ブラウザでの解釈も同じです。
ただし、NekoHtmlの場合は不正な閉じタグのHTMLコメント出力はされません。
> Mayaaで名前空間を扱うためHTMLエレメント名として妥当でないものもパースできる
